"""Versioned Step 10 split, CV, and training-only preprocessing pipeline."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from flowcast.data.artifacts import (
    artifact_record,
    validate_artifact_version,
    write_json,
    write_parquet,
)
from flowcast.modelling.config import load_model_config
from flowcast.modelling.inputs import load_verified_modeling_inputs
from flowcast.modelling.preprocessing import fit_preprocessors
from flowcast.modelling.report import render_modeling_prep_report
from flowcast.modelling.split import assign_chronological_splits
from flowcast.settings import Settings


@dataclass(frozen=True)
class ModelingPrepArtifacts:
    """Paths, frames, and metadata generated by one Step 10 run."""

    version: str
    assignments_path: Path
    folds_path: Path
    schema_path: Path
    summary_path: Path
    markdown_path: Path
    preprocessor_paths: dict[str, Path]
    assignments: pd.DataFrame
    summary: dict[str, Any]


def _training_class_statistics(
    split_summary: dict[str, Any],
    manifest: dict[str, Any],
) -> dict[str, Any]:
    """Derive imbalance weights exclusively from eligible training labels."""

    statistics: dict[str, Any] = {}
    for definition in manifest["targets"]:
        task = str(definition["task"])
        if not task.startswith("classification"):
            continue
        name = str(definition["name"])
        train = split_summary["target_coverage"][name]["train"]
        total = int(train["eligible_rows"])
        if task == "classification_binary":
            positive = int(train["positive_rows"])
            negative = int(train["negative_rows"])
            if not positive or not negative:
                raise RuntimeError(f"Training binary target has one class: {name}")
            statistics[name] = {
                "source_partition": "train",
                "class_counts": {"false": negative, "true": positive},
                "balanced_class_weights": {
                    "false": round(total / (2 * negative), 10),
                    "true": round(total / (2 * positive), 10),
                },
                "scale_pos_weight": round(negative / positive, 10),
            }
        else:
            counts = {
                str(label): int(count)
                for label, count in train["class_counts"].items()
            }
            if not counts or any(count <= 0 for count in counts.values()):
                raise RuntimeError(f"Training multiclass target is incomplete: {name}")
            statistics[name] = {
                "source_partition": "train",
                "class_counts": counts,
                "balanced_class_weights": {
                    label: round(total / (len(counts) * count), 10)
                    for label, count in counts.items()
                },
            }
    return statistics


def _validate_transform_only(
    processors: dict[str, Any],
    validation: pd.DataFrame,
    input_features: list[str],
) -> None:
    sample = validation.loc[:, input_features].head(2_048)
    if sample.empty:
        raise RuntimeError("Validation partition cannot be empty")
    for family, fitted in processors.items():
        values = fitted.processor.transform(sample)
        matrix = np.asarray(values, dtype=float)
        if matrix.ndim != 2 or not np.isfinite(matrix).all():
            raise RuntimeError(f"{family} validation transform is invalid")


def run_modeling_prep(
    settings: Settings,
    version: str | None = None,
) -> ModelingPrepArtifacts:
    """Freeze chronological splits and fit preprocessors on training only."""

    config = load_model_config(settings)
    selected_version = validate_artifact_version(
        version or settings.modelling_version
    )
    inputs = load_verified_modeling_inputs(settings)
    frame = inputs.processed.frame
    assignments, split_summary, folds = assign_chronological_splits(
        frame,
        inputs.processed.manifest,
        config,
    )

    data_dir = settings.processed_dir / selected_version
    assignments_path = data_dir / "assignments.parquet"
    write_parquet(assignments, assignments_path)

    artifact_dir = settings.artifacts_dir / "features" / selected_version
    model_dir = settings.artifacts_dir / "models" / selected_version
    folds_path = artifact_dir / "cv_folds.json"
    schema_path = artifact_dir / "feature_schema.json"
    summary_path = artifact_dir / "summary.json"
    markdown_path = artifact_dir / "summary.md"
    folds_payload: dict[str, Any] = {
        "contract_version": str(config["model_contract_version"]),
        "version": selected_version,
        "strategy": str(config["cross_validation"]["strategy"]),
        "fold_count": len(folds),
        "validation_windows": int(
            config["cross_validation"]["validation_windows"]
        ),
        "gap_windows": int(config["cross_validation"]["gap_windows"]),
        "maximum_horizon_windows": max(
            inputs.processed.manifest["forecast_horizons"]
        ),
        "folds": folds,
    }
    write_json(folds_payload, folds_path)

    train_selected = assignments["split"].eq("train")
    validation_selected = assignments["split"].eq("validation")
    train = frame.loc[train_selected]
    validation = frame.loc[validation_selected]
    class_statistics = _training_class_statistics(
        split_summary,
        inputs.processed.manifest,
    )
    groups, processors = fit_preprocessors(
        train,
        inputs.feature_manifest["features"],
        config,
        model_dir,
        settings,
    )
    _validate_transform_only(
        processors,
        validation,
        list(groups.input_features),
    )

    family_metadata = {
        family: fitted.metadata for family, fitted in processors.items()
    }
    schema: dict[str, Any] = {
        "contract_version": str(config["model_contract_version"]),
        "version": selected_version,
        "input_feature_version": settings.feature_version,
        "feature_count": len(groups.input_features),
        "input_features": inputs.feature_manifest["features"],
        "groups": {
            "numeric": list(groups.numeric),
            "bounded_numeric": list(groups.bounded_numeric),
            "binary": list(groups.binary),
            "categorical": list(groups.categorical),
        },
        "excluded_roles": [
            "keys",
            "identifiers",
            "timestamps",
            "raw_lineage",
            "targets",
            "target_availability",
        ],
        "fitted_on": {
            "partition": "train",
            "row_count": len(train),
            "timestamp_start": train["timestamp"].min().isoformat(),
            "timestamp_end": train["timestamp"].max().isoformat(),
        },
        "validation_mode": "transform_only",
        "test_access_default": "sealed",
        "training_class_statistics": class_statistics,
        "families": family_metadata,
        "input_feature_manifest": artifact_record(
            inputs.feature_manifest_path, settings
        ),
    }
    write_json(schema, schema_path)

    preprocessor_records = {
        family: fitted.metadata["artifact"]
        for family, fitted in processors.items()
    }
    summary: dict[str, Any] = {
        "contract_version": str(config["model_contract_version"]),
        "version": selected_version,
        "input_processed_version": settings.processed_version,
        "input_feature_version": settings.feature_version,
        "configuration": {
            "base": artifact_record(settings.config_path, settings),
            "models": artifact_record(settings.models_config_path, settings),
            "features": artifact_record(settings.features_config_path, settings),
        },
        "input_eda_summary": artifact_record(inputs.eda_path, settings),
        "input_processed": {
            "dataset": artifact_record(inputs.processed.path, settings),
            "manifest": artifact_record(inputs.processed.manifest_path, settings),
            "summary": artifact_record(inputs.processed.summary_path, settings),
        },
        "input_feature_manifest": artifact_record(
            inputs.feature_manifest_path, settings
        ),
        "split": split_summary,
        "cross_validation": folds_payload,
        "preprocessing": {
            "fitted_on_partition": "train",
            "training_rows": len(train),
            "validation_rows_transformed": len(validation),
            "test_rows_loaded_for_tuning": 0,
            "test_access_default": "sealed",
            "feature_count": len(groups.input_features),
            "training_class_statistics": class_statistics,
            "families": family_metadata,
        },
        "artifacts": {
            "assignments": artifact_record(assignments_path, settings),
            "cv_folds": artifact_record(folds_path, settings),
            "feature_schema": artifact_record(schema_path, settings),
            "preprocessors": preprocessor_records,
        },
        "checks": [
            {"name": "every_origin_assigned_once", "passed": True},
            {"name": "train_precedes_validation_precedes_test", "passed": True},
            {"name": "targets_remain_inside_origin_partition", "passed": True},
            {"name": "cv_restricted_to_training", "passed": True},
            {"name": "preprocessors_fit_on_training_only", "passed": True},
            {"name": "test_sealed_by_default", "passed": True},
        ],
    }
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.write_text(
        render_modeling_prep_report(summary),
        encoding="utf-8",
        newline="\n",
    )
    summary["artifacts"]["report"] = artifact_record(markdown_path, settings)
    write_json(summary, summary_path)
    return ModelingPrepArtifacts(
        version=selected_version,
        assignments_path=assignments_path,
        folds_path=folds_path,
        schema_path=schema_path,
        summary_path=summary_path,
        markdown_path=markdown_path,
        preprocessor_paths={
            family: fitted.path for family, fitted in processors.items()
        },
        assignments=assignments,
        summary=summary,
    )
